### ISSUE TITLE
Performance issues in SystemHeat modules

### ISSUE THREAD

**Issue by JonnyOThan** [post-kerbin-mining-corporation/SystemHeat#108]
![image](https://github.com/post-kerbin-mining-corporation/SystemHeat/assets/9804078/1ad14b80-053d-4845-8ab8-33cd061bc673)

![image](https://github.com/post-kerbin-mining-corporation/SystemHeat/assets/9804078/48e22b91-ec40-4dc2-bb54-6850f954fd26)

![image](https://github.com/post-kerbin-mining-corporation/SystemHeat/assets/9804078/6a41bf5a-63b0-49d2-b5cd-2b384b3b43f8)

**Comment by ChrisAdderley** [comment]
Improved a fair bit in 0.7.0
