### ISSUE TITLE
How to make MKS drills and converter work with this mod?

### ISSUE THREAD

**Issue by Ihmosky2** [post-kerbin-mining-corporation/SystemHeat#109]
I am noob .
I tried to add a patch cfg file , but it didnt work .MKS drills and converter have some non-squad moudel to do work.Perhaps need to do change some code?

**Comment by Pasture1** [comment]
Admittedly, I don't know much about configs for systemheat but I pretty sure that they have implement support for different modded modules, while the the stock ones are already implemented.

**Comment by ChrisAdderley** [comment]
https://forum.kerbalspaceprogram.com/topic/193909-112x-systemheat-a-replacement-for-the-coreheat-system-november-20/?do=findComment&comment=4421502

Check this that a user did
