### ISSUE TITLE
Fuel boils off on high timewarp

### ISSUE THREAD

**Issue by Ferristik** [post-kerbin-mining-corporation/SystemHeat#117]
On high timewarp, even though enough EC is being generated, the EC storage goes to 0 therefore fuel boils off. any way to fix this?

normal timewarp (1x)
![resim](https://github.com/user-attachments/assets/8cca2696-2c9b-4892-b161-02f08feae861)

50000x timewarp
![resim](https://github.com/user-attachments/assets/1d474552-f21f-48a3-a80a-1b243564480d)

500000x timewarp
![resim](https://github.com/user-attachments/assets/da6294a7-19f0-448c-b2ba-0ca818c25af5)

**Comment by ChrisAdderley** [comment]
I dn't think this is the right repo to post this in, but...

If you don't have this installed, install it: https://github.com/post-kerbin-mining-corporation/DynamicBatteryStorage.

If you do have that mod installed, and it doesn't help, post detailed information (modlist, logfile, comprehensible images of craft with a minimal modset, and a craft file) in the CryoTanks repo.

**Comment by Ferristik** [comment]
Alright, i will open another issue with more info on CryoTanks.

**Comment by ChrisAdderley** [comment]
Fixed in DBS 2.3.2
