### ISSUE TITLE
ModuleSystemHeatConverter produces heat even if converter not running

### ISSUE THREAD

**Issue by Starstrider42** [post-kerbin-mining-corporation/SystemHeat#126]
I've found a bug where converters produce heat while enabled but not running. This happens whether they're not running for lack of inputs or excess outputs.

I can produce this bug with nothing more than KSP 1.12.5, System Heat 0.8.0, MM 4.2.3, and CRP v112.0.1.

### Steps to reproduce

1. Create a spacecraft with a Convert-O-Tron 125, ore tanks, LFO tanks, power/control, and optionally sufficient radiators. Leave the LFO tanks empty, full, or partially full, depending on whether you want to test behavior with missing inputs or outputs.
2. Deploy to launchpad.
3. Turn on LFO production. With a probe core, the converter consumes 0.125 ore/s and 1.5 EC/s and produces 0.025 propellant/s and 20 kW waste heat.
4. Wait for either ore or spare LFO tankage to be depleted. The converter stops consuming EC (can be verified with Dynamic Battery Storage or by retracting solar panels), but still produces 20 kW heat. It can even overheat if you turn off radiators!

![screenshot5_sm](https://github.com/user-attachments/assets/bae7d76f-7ee9-4420-8b4a-ae82acc451b9)

(For full disclosure, I first spotted this bug with a custom patch for fuel cells, where the problem was that the cell produced full heat even if it was running just enough to "top up" the craft's batteries.)

### Desired behavior

Converters should only produce heat while they are doing work (I've confirmed that this is the behavior in stock). I assume heat production should _not_ scale with productivity, also as in stock.

**Comment by ChrisAdderley** [comment]
Fixed in 0.8.1

**Comment by Starstrider42** [comment]
Hmm... not quite. In 0.8.1, the converter _reports_ that it generates no heat once its output is blocked, but it doesn't cool down unless you actually turn it off.

Even stranger, if you leave it enabled-but-not-running below the loop's target temperature, the loop will stay at that intermediate temperature. In other words, it behaves as if the converter were producing exactly enough heat to counteract the radiators (and yes, it holds that temperature even if you turn off all radiators, a la #127).
