### ISSUE TITLE
Some things cannot be translated

### ISSUE THREAD

**Issue by ra4nd0m** [post-kerbin-mining-corporation/SystemHeat#18]
Several things cannot be translated
Such as:
Dump Rate, Storage Accepted -- PSK-200 Heat Sink
SystemHeat Toolbar window cannot be translated.

**Comment by ChrisAdderley** [comment]
Ok, I will take a pass next release - maybe make me a list after that is done so I don't miss anything

**Comment by ChrisAdderley** [comment]
Note that the reactor panel is currently completely unlocalized too, need to fix this.
