### ISSUE TITLE
Patch for Heat Control missing conformal radiators

### ISSUE THREAD

**Issue by danfarnsy** [post-kerbin-mining-corporation/SystemHeat#23]
Conformal radiators YF-25 (1.25 m), YF-75 (2.5 m), and YF-150 (3.75m) do not have System Heat patches

Edit: I misunderstood which conformal radiators were referred to in the patch, e.g. radiator-conformal-3, which seem to be the GR series.

**Comment by ChrisAdderley** [comment]
Yes this is known, there is a note in the patch file.
