### ISSUE TITLE
lithiumISRU patch generates harmless warnings.

### ISSUE THREAD

**Issue by Gabe-Venberg** [post-kerbin-mining-corporation/SystemHeat#32]
[WRN 02:03:10.600] more than one pass specifier detected, ignoring all but the first: SystemHeatConverters/NearFuturePropulsion/SystemHeatLithiumISRU/@PART[ISRU]:FOR[z_SystemHeat]:                               AFTER[NearFuturePropulsion|FarFutureTechnologies]
 [WRN 02:03:10.600] more than one pass specifier detected, ignoring all but the first: SystemHeatConverters/NearFuturePropulsion/SystemHeatLithiumISRU/@PART[MiniISRU]:FOR[z_SystemHeat]:                           AFTER[NearFuturePropulsion|FarFutureTechnologies]
 [WRN 02:03:10.600] more than one pass specifier detected, ignoring all but the first: SystemHeatConverters/NearFuturePropulsion/SystemHeatLithiumISRU/@PART[KKAOSS_ISRU_g]:FOR[z_SystemHeat]:                      AFTER[NearFuturePropulsion|FarFutureTechnologies]

MM can only have FOR or AFTER, not both. FOR[zz_SystemHeat] should be fine.

**Comment by ChrisAdderley** [comment]
Spent a while tracking this down, turn out that i didn't push some changes before the release last time :|

**Comment by ChrisAdderley** [comment]
Done
