### ISSUE TITLE
MM complained that "Found 1 error in GenericConverters.cfg"

### ISSUE THREAD

**Issue by genehwung** [post-kerbin-mining-corporation/SystemHeat#39]
The error is:
[WRN 20:24:34.005] Cannot find key ConverterName in MODULE
[ERR 20:24:34.005] Error - Cannot parse variable search when inserting new key moduleID = #$ConverterName$
...
[LOG 20:24:34.231] ModuleManager: 7396 patches applied, found <color=yellow>11 warnings</color>, found <color=orange>1 error</color>
1 error related to GameData/genericConverters.cfg

**Comment by ChrisAdderley** [comment]
@Gabe-Venberg maybe take a look at this if you can.

**Comment by genehwung** [comment]
The error seems to be gone in the latest update. Feel free to close this issue.
