### ISSUE TITLE
Heat flux not updating until system has passed ideal heat temperature

### ISSUE THREAD

**Issue by Spacemike** [post-kerbin-mining-corporation/SystemHeat#43]
So, like the title says, I noticed that, unlike in the "Building Cooling Loops" tutorial in the wiki, my vehicles couldn't be brought down below their listed ideal temperatures. In fact, even when I tried the exact same setup in the tutorial, I could not get the current temperature to drop below the ideal temperature. But, when I reverted back to  0.3.2, everything started to work just fine and worked exactly like the tutorial showed. So, I believe this to be some kind of bug that was added in 0.3.3, but I have no clue if anyone else is experiencing this.

On a side note I only have System Heat (along with it's 4 patches), ReStock (and plus), Near Future Electrical, Heat Control, Dynamic Battery Storage, Community Resource Pack, and B9 Part Switch installed when I was testing this.

Screenshot of vehicle in update 0.3.2:
![image](https://user-images.githubusercontent.com/8691038/104822076-29dbf700-580e-11eb-9ddc-2a570645781a.png)

Screenshot of same vehicle in update 0.3.4:
![image](https://user-images.githubusercontent.com/8691038/104822305-7ffd6a00-580f-11eb-98b9-4efbf4573a8f.png)

Screenshot of modified vehicle with way more cooling than needed in update 0.3.4:
![image](https://user-images.githubusercontent.com/8691038/104822342-be932480-580f-11eb-878f-877153db68f2.png)

**Comment by ChrisAdderley** [comment]
This is the correct behaviour. I don't know why I didn't notice when I was describing the tutorial, but there should never be an equilibrium temperature below the nominal loop temperature. It is sometimes possible to have an equilibrium temperature above the loop temp but it's pretty unlikely. One of the changelog items for 0.3.3 indicates 'fixed loop integration' which was causing this bug.

**Comment by Spacemike** [comment]
Aaaaah, okay, I didn't know about that, I read about the loop integration thing, but I wasn't too sure exactly what it meant. The tutorials also threw me off a good deal and the old behavior seemed a bit more normal considering the system seemed to actually cool down and the radiators actually felt like they radiated heat, as the change in the temperature of the system slowed as it neared it's equilibrium point instead of just coming to a stop right at that ideal temperature (which the current system does).

As a side note, there might be a bug in the ability to scroll through the list of heat loops, as, when I try to use the scroll wheel or click and drag, the menu seems to jump around a bit, but doesn't actually let me scroll down.
