### ISSUE TITLE
Log spam

### ISSUE THREAD

**Issue by jinks** [post-kerbin-mining-corporation/SystemHeat#45]
Just installed SystemHeat and wanted to give it a spin, but in the Editor- and FlighScene I immediately notices that the mod is constantly spamming the log with
`[LOG 11:07:13.964] [SystemHeat][SystemHeatOverlay]: No loops, destroying overlay`
there's about 12 entries per second.

adding 1 radiator instead spams
`[LOG 13:16:38.268] [SystemHeat][SystemHeatOverlay]: Loop has < 2 members, hiding`

I somehow doubt that that's intentional, and it can't be good for performance, it also makes it hard to see where other mods are having problems.

**Comment by jinks** [comment]
:facepalm: And here I recompiled the whole thing with the lines commented out...

Should have paid more attention apparently.

**Comment by jinks** [comment]
Just as an FYI, these two message still appear after setting all debug settings to false in Settings.cfg.
(I even tried copying `Settings.cfg` to `settings.cfg`, so it's not a Linux-specific case bug.)

I'm not sure why it is not loading the ConfigNode, but something is off here.

**Comment by ChrisAdderley** [comment]
Yeah... I went to look at this a couple hours ago and noted that those particular messages are not gated behind that flag anyways. So yeah :(. I'll get something to fix it out soon.

**Comment by jinks** [comment]
> are not gated behind that flag anyways. 

What the???
I looked at that code half a dozen times and I did _not see_ that... I just glanced at the `if(` and my brain went to "OK, it's gated."

No hurry though, I can fix it locally until you have time to make a proper release.

**Comment by ChrisAdderley** [comment]
Yeah, hopefully tonight but I've been informed of another bug I need to look into first. 

I should really move all logging to a proper centralized log level handler to avoid the need for these if statements, but haven't got around to it yet.

**Comment by ChrisAdderley** [comment]
This should be resolved in the latest release (0.3.6)
