### ISSUE TITLE
Module Manager errors in "Extras" patch

### ISSUE THREAD

**Issue by AccidentalDisassembly** [post-kerbin-mining-corporation/SystemHeat#46]
[Player.log](https://github.com/post-kerbin-mining-corporation/SystemHeat/files/5845217/Player.log)
ModuleManager reports 5 errors with Extras/SystemHeatConverters/genericConverters.cfg - here's what I think it's referring to in the log:

SystemHeatConverters/genericConverters/@PART[*]:HAS[@MODULE[ModuleResourceConverter]:HAS[@INPUT_RESOURCE:HAS[#ResourceName[ElectricCharge]]]]:FINAL to UmbraSpaceIndustries/WarpDrive/Parts/WarpDrive_250.cfg/PART[USI_WarpDrive]
[WRN 14:26:36.067] Cannot find key ConverterName in MODULE
[ERR 14:26:36.067] Error - Cannot parse variable search when inserting new key moduleID = #$ConverterName$
[LOG 14:26:36.067] Applying update SystemHeatExtraPatches/SystemHeatConverters/genericConverters/@PART[*]:HAS[@MODULE[ModuleResourceConverter]:HAS[@INPUT_RESOURCE:HAS[#ResourceName[ElectricCharge]]]]:FINAL to UmbraSpaceIndustries/WarpDrive/Parts/WarpDrive_625.cfg/PART[USI_WarpDrive_625]
[WRN 14:26:36.067] Cannot find key ConverterName in MODULE
[ERR 14:26:36.067] Error - Cannot parse variable search when inserting new key moduleID = #$ConverterName$
[LOG 14:26:36.067] Applying update SystemHeatExtraPatches/SystemHeatConverters/genericConverters/@PART[*]:HAS[@MODULE[ModuleResourceConverter]:HAS[@INPUT_RESOURCE:HAS[#ResourceName[ElectricCharge]]]]:FINAL to UmbraSpaceIndustries/WarpDrive/Parts/ZWarpDrive125.cfg/PART[ZWarpDrive125]
[WRN 14:26:36.067] Cannot find key ConverterName in MODULE
[ERR 14:26:36.067] Error - Cannot parse variable search when inserting new key moduleID = #$ConverterName$
[LOG 14:26:36.068] Applying update SystemHeatExtraPatches/SystemHeatConverters/genericConverters/@PART[*]:HAS[@MODULE[ModuleResourceConverter]:HAS[@INPUT_RESOURCE:HAS[#ResourceName[ElectricCharge]]]]:FINAL to UmbraSpaceIndustries/WarpDrive/Parts/ZWarpDrive25.cfg/PART[ZWarpDrive25]
[WRN 14:26:36.068] Cannot find key ConverterName in MODULE
[ERR 14:26:36.068] Error - Cannot parse variable search when inserting new key moduleID = #$ConverterName$
[LOG 14:26:36.068] Applying update SystemHeatExtraPatches/SystemHeatConverters/genericConverters/@PART[*]:HAS[@MODULE[ModuleResourceConverter]:HAS[@INPUT_RESOURCE:HAS[#ResourceName[ElectricCharge]]]]:FINAL to UmbraSpaceIndustries/WarpDrive/Parts/ZWarpDrive375.cfg/PART[ZWarpDrive375]
[WRN 14:26:36.068] Cannot find key ConverterName in MODULE
[ERR 14:26:36.068] Error - Cannot parse variable search when inserting new key moduleID = #$ConverterName$
[LOG 14:26:36.069] Applying update

**Comment by ChrisAdderley** [comment]
Generic patch doesn't seem to handle converters that are not well configured (e.g no converter name). Will look into some solution.

**Comment by ChrisAdderley** [comment]
This should be resolved in the latest release (0.3.6). Please let me know as I can't test all edge cases.

**Comment by AccidentalDisassembly** [comment]
> 
> 
> This should be resolved in the latest release (0.3.6). Please let me know as I can't test all edge cases.

Errors are gone with 0.3.6!
