### ISSUE TITLE
Nuclear engine module doesnt seem to work at all.

### ISSUE THREAD

**Issue by EnderiumSmith** [post-kerbin-mining-corporation/SystemHeat#47]
When starting the engine the isp and power sloooowly rise and so does the heat. but once the heat reaches the goal it doesnt stop and keeps rising. the engine will overheat and meltdown before it even gets to full power. Also the power output and temperature goal are weirdly low, like 200kw and 1800k instead of the expected 11000kw and at least 2600k.

The power reactors seem to work better but when shut down they display the last amount if power they made. it even shows up in dynamic battery storage, but its not actually making power. Also the power rises so slowly you ave to timewarp. you could not use them for ion engines without the manual override, and then you would have to remember to turn it back off.

**Comment by ChrisAdderley** [comment]
> When starting the engine the isp and power sloooowly rise and so does the heat. but once the heat reaches the goal it doesnt stop and keeps rising. the engine will overheat and meltdown before it even gets to full power. 

Why would the heat stop when reaching the goal? Use radiators to get rid of the excess heat. 

> Also the power output and temperature goal are weirdly low, like 200kw and 1800k instead of the expected 11000kw and at least 2600k.

'Expected'? Working like I expect:
1. Remember that loop temperature is not the inside of the reactor, it's the operating temperature of the cooling loop. 
2. The fluxes represent heat not removed by the exhaust. That's why they're quite low and forgiving to the player. 

> The power reactors seem to work better but when shut down they display the last amount if power they made. it even shows up in dynamic battery storage, but its not actually making power. 

Sure, I can look into that. 

> Also the power rises so slowly you ave to timewarp. you could not use them for ion engines without the manual override, and then you would have to remember to turn it back off.

This is exactly as intended.

**Comment by EnderiumSmith** [comment]
but why would the engine produce waste heat? and would this mean that most of the heat is simply deleted when the engine isnt thrusting? also the trimodal engine have radiator skirts that arent taken into account by this.

what this would mean is the reactor gets forced to 100% and turned on a few minutes before a burn. then suddenly you throttle up. this seems inferior to just having enrU in the fuel definition. that would actually have to U burn actually related to the engine.

also the stock nerva has a cost of 0 and higher mass than the triton with this.

If this is how its supposed to work ill just stick to the stock system where the heat catch up explodes if loaded via rondezvou.

**Comment by ChrisAdderley** [comment]
You may not be the target audience for this mod then! Cheers!
