### ISSUE TITLE
3rd party parts giving exception error on editor

### ISSUE THREAD

**Issue by TheDogKSP** [post-kerbin-mining-corporation/SystemHeat#50]
Non-stock parts from other mods, such as WildBlueIndustries MOLE give errors in editor when adding or removing them, which is weird because that part in the example (WBI.TitanInstrumentUnit) does nothing with CoreHeat or SystemHeat:

Example logs:
[LOG 19:31:22.856] deleting part WBI.TitanInstrumentUnit
[ERR 19:31:22.857] Exception handling event onEditorPartDeleted in class SystemHeatEditor:System.NullReferenceException: Object reference not set to an instance of an object
  at SystemHeat.SystemHeatEditor.onEditorPartDeleted (Part part) [0x00001] in <427c2f422ed84fbf944ba484f0d88fd1>:0 
  at EventData`1[T].Fire (T data) [0x000b0] in <f8bc9e2b903e48a5b248ab0083c07c62>:0 

[EXC 19:31:22.859] NullReferenceException: Object reference not set to an instance of an object
	SystemHeat.SystemHeatEditor.onEditorPartDeleted (Part part) (at <427c2f422ed84fbf944ba484f0d88fd1>:0)
	EventData`1[T].Fire (T data) (at <f8bc9e2b903e48a5b248ab0083c07c62>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:LogException(Exception)
	EventData`1:Fire(Part)
	EditorLogic:<SetupFSM>b__190_30()
	KerbalFSM:RunEvent(KFSMEvent)
	EditorLogic:DestroySelectedPart()
	EditorLogic:OnPartListBackgroundTap()
	EditorLogic:OnPartListIconTap(AvailablePart)
	KSP.UI.Screens.EditorPartList:TapIcon(AvailablePart)
	KSP.UI.Screens.EditorPartIcon:MouseInput_SpawnPart()
	UnityEngine.EventSystems.EventSystem:Update()

**Comment by ChrisAdderley** [comment]
Fixed in 0.3.7
