### ISSUE TITLE
[QUESTION] Mods compatibilites

### ISSUE THREAD

**Issue by Tutul-** [post-kerbin-mining-corporation/SystemHeat#52]
Hi, sound really interesting :-)
But I assume it will not be compatible with Kerbalism as it already manager thermal stuff in background ?
What about parts added by other mods, does it work out of the box with the patch ? If yes, I suppose it will not work with KSPI-E ?

**Comment by ChrisAdderley** [comment]
Not KSPI-E or Kerbalism. They tend to replace all my mods' mechanics. Other mods, well, some will, some won't.

**Comment by Tutul-** [comment]
I wish it was because I would love to have a bigger control on how the flow of head travel within my ship.

Anyway, thanks for the informations :-)
