### ISSUE TITLE
Redo Fission Transfer Mechanics

### ISSUE THREAD

**Issue by ChrisAdderley** [post-kerbin-mining-corporation/SystemHeat#61]
The current concept sucks.

**Comment by FittedOrphan68** [comment]
Hey Chris,
I've been messing around with this, your NF Suite and FFt, as well as too many other mods to mention. With NFE, fuel transfer was pretty straight forward, but this mod removes that mechanic [RadioactiveStorageContainer]. How does one now transfer/refuel? Right clicking both containers does not seem to allow the stock fuel transfer mechanics either.
Point out the obvious for me when you have a moment. Can't fathom how you keep it all straight, appreciate the content/passion!

**Comment by ChrisAdderley** [comment]
Hey thanks! So currently you need to have a Kerbal (engineer) with a nuclear fuel transfer container in their inventory. EVA them, right click on a container with fuel or waste, then click to collect it. Then move the kerbal to the target container, right click it then click to deposit the carried fuel or waste.

This is fun... once or twice. It gets old fast. Next release will have something different, which is simpler: you will be able to use the standard stock pump in/out mechanics with nuclear fuels if you have an engineer of sufficient level on board your vessel.

**Comment by FittedOrphan68** [comment]
Ah ha. I saw that lil guy just didnt make the connection. Thanks a bunch, for the response and goodies alike!

**Comment by ChrisAdderley** [comment]
Implemented in 0.4.0
