### ISSUE TITLE
Disabling Powered Up Reactors With SystemHeat Patch Causes Extreme Overheat

### ISSUE THREAD

**Issue by gajbooks** [post-kerbin-mining-corporation/SystemHeat#64]
Disabling reactors that have gotten up to temperature results in a dramatic overheat of the cooling loop and results in inevitable reactor meltdown when done at full power.

1. Attach reactor module (nuclear engine, reactor, etc) to a sufficient and powered radiator setup.
2. Start reactor. Reactor reaches equilibrium temperature without damage or incident.
3. Shutdown reactor running at full power. Reactor flux starts decreasing, System Temperature changes to (rapidly increasing value)/NaN K
4. Reactor melts down or eventually stops producing heat flux safely. System Temperature changes to (high value)/(ambient) K after heat flux reaches 0 kw but not before.
5. System Temperature achieves equilibrium.

This seems to be some sort of interaction with the expected ambient temperature, or the fact that disabled reactors have residual heat flux? This also occurs during auto-shutdown and hibernation mode, which results in extreme reactor destruction unless manually set to a very low power percentage first.

**Comment by gajbooks** [comment]
(Looking through develop, it looks like this issue may be fixed in the next version from some of the code changes, but I have not verified this.)

**Comment by ChrisAdderley** [comment]
Yes, I'm working on this but haven't had time to finish it yet.

**Comment by ChrisAdderley** [comment]
This was fixed some versions ago.
