### ISSUE TITLE
Implementing drill modules

### ISSUE THREAD

**Issue by Grimmas** [post-kerbin-mining-corporation/SystemHeat#66]
A suggestion for improvement. I found myself writing a SystemHeat patch for another mod that I use and quickly realized that there's no SystemHeat equivalent for ModuleAsteroidDrill and ModuleCometDrill. Since they are not subclassed from ModuleResourceHarvester, I'm guessing they work slightly differently under the hood.

**Comment by ChrisAdderley** [comment]
Yeah... I haven't really found the motivation to investigate this yet.

**Comment by ChrisAdderley** [comment]
Done
