### ISSUE TITLE
Freeze on load with SystemHeatFissionEngines

### ISSUE THREAD

**Issue by SunSerega** [post-kerbin-mining-corporation/SystemHeat#68]
I've made clear installation (core 1.11.2.3077 + both expansions) and used CKAN to install a single mod:
> System Heat - Nuclear Engine Configuration

(+dependancies, obv)

It always freezes right here:
![image](https://user-images.githubusercontent.com/27270190/122904613-2ddde900-d359-11eb-97f4-77b06daf654b.png)

**Comment by ChrisAdderley** [comment]
Interesting edge case. CRP needs to be added to the dependencies for that particular submod.
