### ISSUE TITLE
Fission Engines overheating causes crash at reignition

### ISSUE THREAD

**Issue by Alewx** [post-kerbin-mining-corporation/SystemHeat#71]
After overheating a fission engine like the cherenkov it will shutdown, properly.  Then when cooled down and ready for new movement trying to reignite it including its reactor, it will cause a crash of the game. sadly nothing appears in the ksp.log. but could reproduce it with these simple steps.

**Comment by ChrisAdderley** [comment]
I can't reproduce this unfortunately, but I will keep a look out.

**Comment by Alewx** [comment]
[ksp 1.12 mods.txt](https://github.com/post-kerbin-mining-corporation/SystemHeat/files/6872743/ksp.1.12.mods.txt)
My CKAN mod list, just to be sure, maybe this is already fixed due to some sideeffects. will look it up again.
Thanks for the reply.

**Comment by ChrisAdderley** [comment]
I see KSPIE in there, I would generally expect some kind of horrible conflict to occur.

**Comment by ChrisAdderley** [comment]
This can probably be closed, let me know if you see it more with modern (0.5.5+) versions of this mod.
