### ISSUE TITLE
Medium: Coolant tanks change target temperature of a cooling loop.

### ISSUE THREAD

**Issue by KSP-Rocketeer** [post-kerbin-mining-corporation/SystemHeat#73]
See here: 1st report in Posting
https://forum.kerbalspaceprogram.com/index.php?/topic/193909-111x-systemheat-a-replacement-for-the-coreheat-system-june-4th/page/20/&tab=comments#comment-4000594

**Comment by ChrisAdderley** [comment]
Fixed and in testing for 0.5.0
