### ISSUE TITLE
Major: German localization of SH broken, so that nuclear fuel transfers are not possible

### ISSUE THREAD

**Issue by KSP-Rocketeer** [post-kerbin-mining-corporation/SystemHeat#75]
The german localization of SH is broken in a away, that it does not enable nuclear fuel transfers anymore. This is due to the new reactor mechanics, that come with SH.

See our conversation on this topic here:
https://forum.kerbalspaceprogram.com/index.php?/topic/193909-111x-systemheat-a-replacement-for-the-coreheat-system-june-4th/page/20/&tab=comments#comment-4001925

In the end we came to the conclusion, that the german localization causes this.

**Comment by ChrisAdderley** [comment]
Fixed and in testing for 0.5.0
