### ISSUE TITLE
Medium: some heat generation/rejection combinations create wild oszillations in temperature approx. mechanism in VAB.

### ISSUE THREAD

**Issue by KSP-Rocketeer** [post-kerbin-mining-corporation/SystemHeat#76]
All details and screenshots please find here:
https://forum.kerbalspaceprogram.com/index.php?/topic/193909-111x-systemheat-a-replacement-for-the-coreheat-system-june-4th/page/21/&tab=comments#comment-4003392

**Comment by ChrisAdderley** [comment]
Fixed and in testing for 0.5.0
