### ISSUE TITLE
Universal harvester patch might be screwy

### ISSUE THREAD

**Issue by ChrisAdderley** [post-kerbin-mining-corporation/SystemHeat#89]
See https://forum.kerbalspaceprogram.com/index.php?/topic/193909-112x-systemheat-a-replacement-for-the-coreheat-system-october-3/&do=findComment&comment=4031720

**Comment by Rodg88** [comment]
Might just be line 29 in genericHarvesters.cfg needs a capital E: `!ThermalEfficiency {}` vs `!Thermalefficiency {}`

**Comment by Krzeszny** [comment]
> Might just be line 29 in genericHarvesters.cfg needs a capital E: `!ThermalEfficiency {}` vs `!Thermalefficiency {}`

It works with this fix
