### ISSUE TITLE
System heat crashes the game and breaks ksp.log

### ISSUE THREAD

**Issue by harrytherocketeer** [post-kerbin-mining-corporation/SystemHeat#92]
@ChrisAdderley The problem appeared after I installed Principia, but according to the last texts by ksp.log it states it's System Heat destroying the toolbar. The log refuses to update ever since.
[KSP.log](https://github.com/post-kerbin-mining-corporation/SystemHeat/files/7931318/KSP.log)

**Comment by ChrisAdderley** [comment]
It's difficult if not impossible to debug this kind of thing. Unfortunately due to the level at which Principia modifies the game, this should be pushed to the Principia devs. I doubt it's anything to do with SH.
