### ISSUE TITLE
LV-N "Nerv" Have no system heat module?

### ISSUE THREAD

**Issue by jupiterbjy** [post-kerbin-mining-corporation/SystemHeat#93]
Since that this don't overheat on it's own, I am not sure if LV-N is intended to not have radiator/loop support at all. Is this a bug?

If this indeed is a bug, let me know if there's something I should provide, like logs, mods, etc

![image](https://user-images.githubusercontent.com/26041217/152542203-353cc6ec-2cde-4521-90b3-55f06f6749e6.png)

**Comment by ChrisAdderley** [comment]
It's intentional. The engine can be cooled completely by its own exhaust.
